# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chinmay Talegaonkar
full_name: Chinmay Talegaonkar
email: chinmay0301@gmail.com
email2: chinmay0301@iitb.ac.in
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chinmay0301.github.io" # the base hostname & protocol for your site
github_username:  chinmay0301 
linkedin_username: chinmay0301
include: ['_pages']
footer-links-active:
  stackoverflow: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
